homework with testing and multiprocessing
chusovaelisa/chusova-python-2k-11-200 pull request #8
Opened 2023-10-16 13:35 UTC by chusovaelisa

2023-10-17 06:59 UTC, atnarturuni requested changes

2023-10-17 06:59 UTC, atnarturuni commented on link_normalization_test.py
> +def normalize_image_url(image_url):
2 переноса

2023-10-17 06:59 UTC, atnarturuni commented on link_normalization_test.py
> +image_url3 = "/200.jpg"
нужно использовать параметризацию

2023-10-17 06:59 UTC, atnarturuni commented on link_normalization_test.py
> +    parsed_url = urllib.parse.urlparse(image_url)
с помощью urllib.parse можно и протокол проверять)

2023-10-17 06:59 UTC, atnarturuni commented on multiprocessing.py
> +    download_all_images(page_url, save_folder)
где multiprocessing?

2023-10-17 06:59 UTC, atnarturuni commented on link_normalization_test.py
> +    assert normalize_image_url(image_url3) == "http:/200.jpg"
на выходе получается некорректная ссылка

2023-10-17 15:47 UTC, atnarturuni commented on link_normalization_test.py
> +    parsed_url = urllib.parse.urlparse(image_url)
зачем дважды делать одну и ту же операцию?

2023-10-17 15:47 UTC, atnarturuni requested changes

2023-10-17 15:47 UTC, atnarturuni commented on link_normalization_test.py
> +def test_normalize_image_url(image_url, expected_url):
между декоратором и функцией не может быть переносов, это одно целое

2023-10-17 15:47 UTC, atnarturuni commented on multiprocessing.py
> +from bs4 import BeautifulSoup
где переносы между системными и библиотеками?

2023-10-17 15:47 UTC, atnarturuni commented on multiprocessing.py
> +    return urljoin(base_url, image_url)
зачем функцию переименовывать?

2023-10-17 15:48 UTC, atnarturuni commented on multiprocessing.py
> +        pool.close()
сделай через контекстный менеджер

2023-10-24 06:36 UTC, atnarturuni commented on link_normalization_test.py
> +    parsed_url = urllib.parse.urlparse(image_url)
не исправлено

2023-10-24 06:36 UTC, atnarturuni commented on link_normalization_test.py
> +@pytest.mark.parametrize("image_url, expected_url", [
где переносы?

2023-10-24 06:36 UTC, atnarturuni commented on multiprocessing.py
> +from multiprocessing import Pool
это системный импорт, он должен быть в начале

2023-10-31 06:30 UTC, atnarturuni requested changes
не все исправлено

2023-11-21 05:43 UTC, atnarturuni commented on link_normalization_test.py
> +    parsed_url = urllib.parse.urlparse(image_url)
?

2023-11-21 05:43 UTC, atnarturuni commented on multiprocessing.py
> +    return urljoin(base_url, image_url)
?

2023-12-12 06:10 UTC, atnarturuni commented on multiprocessing.py
> +    return urljoin(base_url, image_url)
?

2023-12-12 06:11 UTC, atnarturuni commented on link_normalization_test.py
> +    ("/200.jpg", "http:/200.jpg")
на выходе получается некорректная ссылка

2023-12-12 12:08 UTC, atnarturuni commented on link_normalization_test.py
> +    ("/200.jpg", "http://http.cat/200.jpg")
а откуда домен возьмется?

2023-12-18 05:57 UTC, chusovaelisa commented on multiprocessing.py
> +    return urljoin(base_url, image_url)
я не помню как как она до этого называлась :/

2023-12-18 16:00 UTC, atnarturuni commented on multiprocessing.py
> +    return urljoin(base_url, image_url)
У тебя есть urljoin, который принимает base_url и image_url. И есть твоя функция с такими же параметрами, которая вызывает urljoin. Получается, ты делаешь лишнюю обертку, которая ничего нового не привносит. Не надо так

2023-12-18 16:01 UTC, atnarturuni requested changes
исправь переименование функции

2023-12-22 03:58 UTC, atnarturuni approved these changes

2023-12-22 03:58 UTC, merged